import { useRouter } from 'next/router';

import { DownloadFile } from '../components/fileDownloader/DownloadFile';
import Head from 'next/head';


export default function Download(){

    const router = useRouter();

    return (
        
        <>
            {/* <Head>
                <title>SafeSender</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo2.svg" />
            </Head> */}
            <DownloadFile token={router.query['token'] as string} />
        </>
    )
}