import Head from 'next/head';
import Image from 'next/image';
import Script from "next/script"
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { Poppins } from 'next/font/google';

import waves from '../../public/waves.svg';

import MainBox from '../components/mainBox/MainBox';
import { Footer } from '../components/shared/footer/Footer';
import { Header } from '../components/shared/header/Header';

import { ThemeProvider, useTheme } from '../core/context/ThemeContext';
import { LoaderProvider, useLoader } from '../core/context/LoaderContext';
import { Loader } from '../components/shared/loader/Loader';
import ErrorDialog from '../components/shared/errorDialog/ErrorDialog';


const poppinsFont = Poppins( { weight: [ '400', '500', '600' ], subsets: [ 'latin' ] } );

export default function Home() {

  const loader = useLoader();

  return (
    <>

      {/* <Head>
        <title>SafeSender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo2.svg" />
      </Head> */}
  
      <MainBox/>
    </>
  )
}
