import Head from 'next/head'
import { Poppins } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '../components/shared/header/Header';

const poppinsFont = Poppins( { weight: [ '400', '500', '600' ], subsets: [ 'latin' ] } );

export default function Home() {
  return (
    <>
      <Head>
        <title>SafeSender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Header />

      <main className='bg-[#F5F5F5] h-56'>


      </main>
    </>
  )
}
