import Head from 'next/head'
import { Poppins } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '../components/shared/header/Header';
import { ThemeProvider, useTheme } from '../core/context/ThemeContext';
import waves from '../../public/Group (1).svg';
import Image from 'next/image';

const poppinsFont = Poppins( { weight: [ '400', '500', '600' ], subsets: [ 'latin' ] } );

export default function Home() {

  const theme = useTheme();

  console.log(theme.darkMode);

  return (
    <>
      <Head>
        <title>SafeSender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <ThemeProvider>
        <div className={`${ theme.darkMode ? 'dark' : '' }`}>
          <Header />

          <main className='bg-blue h-[800px] dark:bg-black overflow-hidden'>
          
            <Image className='ml-[0px] mt-[-50px] w-full object-fill' src={waves} alt='bg'></Image>

          </main>
        </div>

      </ThemeProvider>
    </>
  )
}
